import { createFileRoute, Link, useNavigate, useParams } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { SiteHeader } from "@/components/SiteHeader";
import { chatters, completeChat, fmt, getChatMessages, getChatSession, loadAccount, sendChatMessage, type Account, type ChatMessage } from "@/lib/data";

export const Route = createFileRoute("/chat/$slug")({ component: ChatPage });
function ChatPage() {
  const {slug}=useParams({from:"/chat/$slug"}); const navigate=useNavigate(); const person=chatters.find(c=>c.slug.toLowerCase()===slug.toLowerCase()); const [account,setAccount]=useState<Account|null>(null);
  useEffect(()=>{void loadAccount().then(setAccount)},[]);
  if(!person)return <><SiteHeader/><p className="p-8 text-center">Mtumiaji hakupatikana.</p></>;
  if(!account?.username)return <div className="min-h-screen bg-background"><SiteHeader/><main className="mx-auto max-w-lg p-4"><section className="card-soft p-6 text-center"><img src={person.avatar} className="mx-auto size-28 rounded-full border-4 border-primary"/><h2 className="mt-4 text-2xl font-bold">{person.name} {person.emoji}</h2><p className="mt-3 text-muted-foreground">Jisajili na lipia activation fee ili kuanza chat.</p><Link to="/register" search={{chat:person.slug}} className="mt-5 block rounded-xl bg-primary py-3.5 font-bold text-primary-foreground">📝 Jisajili Ili Kuendelea</Link></section></main></div>;
  if(account.status!=="approved")return <div className="min-h-screen bg-background"><SiteHeader/><main className="mx-auto max-w-lg p-4"><section className="card-soft p-6 text-center"><h2 className="text-xl font-bold">Akaunti inasubiri approval</h2><p className="mt-2 text-sm text-muted-foreground">Admin akithibitisha malipo yako utaweza kufikia dashboard na kuendelea na {person.name}.</p><Link to="/payment" className="mt-5 block rounded-xl bg-primary py-3 font-bold text-primary-foreground">Angalia Malipo</Link></section></main></div>;
  return <div className="min-h-screen bg-background pb-10"><SiteHeader/><div className="flex items-center gap-3 border-b border-primary/30 bg-card px-3 py-3"><Link to="/dashboard" className="px-1 text-xl">←</Link><img src={person.avatar} className="size-12 rounded-full border-2 border-primary"/><div><h1 className="text-xl font-bold">{person.name} {person.emoji}</h1><p className="text-[13px] font-semibold text-online">● online</p></div></div><main className="mx-auto max-w-lg px-3 py-4"><LiveChat person={person} account={account} onFinish={()=>navigate({to:"/dashboard"})}/></main></div>;
}

function LiveChat({person,account,onFinish}:{person:(typeof chatters)[number];account:Account;onFinish:()=>void}) {
  const [sessionId,setSessionId]=useState(""); const [messages,setMessages]=useState<ChatMessage[]>([]); const [input,setInput]=useState(""); const [sending,setSending]=useState(false); const [seconds,setSeconds]=useState(0); const [error,setError]=useState(""); const endRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{void (async()=>{try{const s=await getChatSession(person.slug,person.tzs);setSessionId(s.id);setMessages(await getChatMessages(s.id));}catch(e){setError(e instanceof Error?e.message:"Chat haijafunguka")}})()},[person]);
  useEffect(()=>{const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[]); useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"})},[messages]);
  const replies=["Asante sana, hii inanisaidia kujifunza!","Nieleze zaidi tafadhali 😊","Umeeleza vizuri sana, endelea.","Hii ni nzuri! Neno hilo linamaanisha nini?"];
  const send=async()=>{const text=input.trim();if(!text||!sessionId||sending)return;setSending(true);setError("");try{const s=await sendChatMessage(sessionId,text);setMessages(m=>[...m,{id:crypto.randomUUID(),from:"me",text,created_at:new Date().toISOString()}]);setInput("");setTimeout(()=>setMessages(m=>[...m,{id:crypto.randomUUID(),from:"them",text:replies[m.filter(x=>x.from==="me").length%replies.length]!,created_at:new Date().toISOString()}]),700);if(s.message_count>=20){await completeChat(sessionId);setTimeout(onFinish,900)}}catch(e){setError(e instanceof Error?e.message:"Ujumbe haujatumwa") }finally{setSending(false)}};
  const count=messages.filter(m=>m.from==="me").length; const done=count>=20;
  return <section className="card-soft flex flex-col overflow-hidden"><div className="flex items-center justify-between bg-success-soft px-4 py-2 text-[13px] font-semibold text-success"><span>Muda: {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")}</span><span>Malipo: TZS {fmt(person.tzs)}</span></div><div className="flex items-center justify-between border-b px-4 py-2 text-xs"><span>Ujumbe: {count}/20</span>{done&&<b className="text-success">Chat imefungwa • malipo yameongezwa</b>}</div><div className="flex max-h-[55vh] min-h-[45vh] flex-col gap-2 overflow-y-auto p-3">{messages.length===0&&<div className="mr-auto max-w-[80%] rounded-2xl rounded-bl-sm bg-muted px-3 py-2 text-sm">Habari! Mimi ni {person.name}. Tuanze kuzungumzia {person.wants}?</div>}{messages.map(m=><div key={m.id} className={m.from==="me"?"ml-auto max-w-[80%] rounded-2xl rounded-br-sm bg-primary px-3 py-2 text-sm text-primary-foreground":"mr-auto max-w-[80%] rounded-2xl rounded-bl-sm bg-muted px-3 py-2 text-sm"}>{m.text}</div>)}<div ref={endRef}/></div><div className="flex gap-2 border-t p-3"><input disabled={done||sending} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void send()}} placeholder={done?"Chat imefungwa":"Andika ujumbe..."} className="flex-1 rounded-full border bg-background px-4 py-2.5 text-sm"/><button disabled={done||sending} onClick={()=>void send()} className="rounded-full bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-50">{sending?"...":"Tuma"}</button></div>{error&&<p className="px-3 pb-2 text-xs font-semibold text-destructive">{error}</p>}<div className="px-3 pb-3 text-center text-xs text-muted-foreground">Ukifikisha ujumbe 20, chat itafungwa na TZS {fmt(person.tzs)} itaongezwa kwenye balance yako.</div></section>;
}
