import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { SiteHeader } from "@/components/SiteHeader";
import { chatters, createWithdrawal, fmt, loadAccount, type Account } from "@/lib/data";

export const Route = createFileRoute("/dashboard")({ component: Dashboard });
type WStage = "closed" | "form" | "processing" | "sent";

function Dashboard() {
  const [account, setAccount] = useState<Account | null>(null);
  const [wStage, setWStage] = useState<WStage>("closed");
  const [wAmount, setWAmount] = useState(""); const [wPhone, setWPhone] = useState(""); const [wError, setWError] = useState(""); const [wSent, setWSent] = useState({amount:0,phone:""});
  const sync = () => void loadAccount().then((a) => { if (!a.username) window.location.href="/register"; else if (a.status !== "approved") window.location.href="/payment"; else setAccount(a); });
  useEffect(() => { sync(); window.addEventListener("dolaway-account", sync); return () => window.removeEventListener("dolaway-account", sync); }, []);
  const available = chatters.filter(c => !(account?.completed ?? []).includes(c.slug));
  const openWithdraw = () => { setWError(""); setWAmount(""); setWPhone(account?.phone ?? ""); setWStage("form"); };
  const submitWithdraw = async () => { const amount=Number(wAmount.replace(/\D/g,"")); const phone=wPhone.trim(); if(!amount||amount<50000)return setWError("Kiasi cha chini ni TZS 50,000."); if(amount>(account?.balance??0))return setWError("Salio lako halitoshi."); if(!/^0[67]\d{8}$/.test(phone))return setWError("Namba ya simu si sahihi (mfano 0712345678)."); setWError(""); setWStage("processing"); try { await createWithdrawal(amount,phone); setWSent({amount,phone}); setWStage("sent"); sync(); } catch(e){ setWStage("form"); setWError(e instanceof Error?e.message:"Withdrawal imeshindikana."); } };
  if (!account) return <main className="min-h-screen flex items-center justify-center">Inapakia...</main>;
  return <div className="min-h-screen bg-background pb-16"><SiteHeader/><main className="mx-auto max-w-lg px-3 py-5">
    <section onClick={openWithdraw} className="cursor-pointer rounded-2xl bg-brand-deep px-5 py-6 text-center"><p className="text-[12px] font-bold tracking-[0.2em] text-brand-foreground/70">SALIO LAKO</p><p className="mt-1 text-[36px] font-black text-gold">TZS {fmt(account.balance)}</p><p className="mt-1 text-[13px] text-brand-foreground/80">Karibu {account.fullName || "mtumiaji"} • akaunti imeidhinishwa ✓</p><button onClick={(e)=>{e.stopPropagation();openWithdraw();}} disabled={account.balance<50000} className="mt-4 w-full rounded-full bg-primary py-3 text-[15px] font-bold text-primary-foreground disabled:opacity-50">💰 Withdraw</button><p className="mt-2 text-[11px] text-brand-foreground/60">Kiwango cha chini cha kutoa ni TZS 50,000</p></section>
    <h2 className="mt-6 text-[16px] font-bold text-foreground">Chats zinazopatikana</h2><div className="mt-3 space-y-3">{available.map(c=><Link key={c.slug} to="/chat/$slug" params={{slug:c.slug}} className="card-soft flex items-center gap-3 p-3"><img src={c.avatar} alt={c.name} className="size-11 rounded-full border-2 border-primary object-cover"/><div className="min-w-0 flex-1"><p className="text-[15px] font-bold">{c.name} {c.emoji}</p><p className="truncate text-[12px] text-muted-foreground">{c.wants}</p></div><span className="rounded-md bg-brand-deep px-2.5 py-1 text-[12px] font-black text-brand-foreground">TZS {fmt(c.tzs)}</span></Link>)}</div>
    {account.completed.length>0&&<><h2 className="mt-6 text-[16px] font-bold">Zilizokamilika</h2><ul className="mt-2 space-y-2">{account.completed.map(slug=>{const c=chatters.find(x=>x.slug===slug);return <li key={slug} className="card-soft flex items-center justify-between p-3 text-[14px]"><span className="font-semibold">{c?.name??slug}</span><span className="font-bold text-success">+ TZS {fmt(c?.tzs??0)}</span></li>})}</ul></>}
  </main>
  {wStage!=="closed"&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/50 px-3"><div className="w-full max-w-md rounded-3xl bg-card p-5">{wStage==="form"&&<><h2 className="text-xl font-black">Withdrawal</h2><p className="mt-1 text-sm text-muted-foreground">Balance: TZS {fmt(account.balance)}</p><label className="mt-5 block text-sm font-bold">Kiasi (TZS)</label><input inputMode="numeric" value={wAmount} onChange={e=>setWAmount(e.target.value)} placeholder="50000" className="mt-2 w-full rounded-xl border px-4 py-3"/><label className="mt-4 block text-sm font-bold">Namba ya simu</label><input inputMode="numeric" value={wPhone} onChange={e=>setWPhone(e.target.value)} placeholder="0712345678" className="mt-2 w-full rounded-xl border px-4 py-3"/>{wError&&<p className="mt-2 text-sm font-semibold text-destructive">{wError}</p>}<button onClick={()=>void submitWithdraw()} className="mt-5 w-full rounded-full bg-success py-3.5 font-bold text-success-foreground">WITHDRAWAL</button><button onClick={()=>setWStage("closed")} className="mx-auto mt-4 block text-sm underline">Ghairi</button></>}{wStage==="processing"&&<div className="py-10 text-center"><div className="mx-auto size-12 animate-spin rounded-full border-4 border-muted border-t-success"/><p className="mt-4 font-semibold">Inatuma withdrawal...</p></div>}{wStage==="sent"&&<div className="py-8 text-center"><div className="mx-auto flex size-14 items-center justify-center rounded-full bg-success text-2xl text-success-foreground">✓</div><p className="mt-4 text-lg font-bold text-success">Withdrawal Successful</p><p className="mt-1 text-sm text-muted-foreground">TZS {fmt(wSent.amount)} imekatwa kwenye balance na imewekwa kwenye namba {wSent.phone}.</p><button onClick={()=>setWStage("closed")} className="mt-5 w-full rounded-full bg-success py-3.5 font-bold text-success-foreground">SAWA</button></div>}</div></div>}
  </div>;
}
